name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        OPENETHEREUM_IMAGE_REPO=rubo/openethereum \
        OPENETHEREUM_BUILDER_IMAGE_TAG=build-latest \
        OPENETHEREUM_RUNNER_IMAGE_TAG=centos-openethereum-experimental \
        ./scripts/docker/centos/build.sh
